### ISSUE TITLE
Where can I these icons?

### ISSUE THREAD

**Issue by idontlikecaesar** [4lmost/BitBetter#1]
Hey there. Theme looks okay but what caught my attention was [this](https://user-images.githubusercontent.com/88981092/129486505-71d6e6c8-2d6c-4b0e-940d-fca99f8c3e6b.png)  . Are these OneUI icons and where can I find them?

**Comment by 4lmost** [comment]
https://www.opendesktop.org/p/1561814
Here ya go :)

Il Sab 21 Ago 2021, 19:39 idontlikecaesar ***@***.***> ha
scritto:

**Comment by idontlikecaesar** [comment]
Thanks a lot!
